# ~/.config/starship.toml

add_newline = true
format = """
$directory$git_branch$git_status$nodejs$python$rust$golang
$character"""

[directory]
style = "bold cyan"
truncation_length = 4
truncate_to_repo = true
read_only = " "
home_symbol = "~"

[git_branch]
symbol = " "
style = "bold purple"
format = "$symbol$branch "

[git_status]
style = "bold yellow"
format = "($all_status$ahead_behind) "
conflicted = " "
ahead = "⇡${count}"
behind = "⇣${count}"
staged = "+${count}"
modified = "~${count}"
deleted = "×${count}"
untracked = "?${count}"

[character]
success_symbol = "❯"
error_symbol = "❯"
